#### pytorch 初学

##### Tensors

 Tensors 与numpy 中的ndarrays很像，pytorch可以支持GPU操作

In [1]:
from __future__ import print_function
import torch

##### 创建空的tensor

In [2]:
x = torch.empty(5,3) # 5行3列的空的tensors
print(x)

tensor([[1.8961e-34, 0.0000e+00, 1.8961e-34],
        [0.0000e+00, 1.8962e-34, 0.0000e+00],
        [1.8962e-34, 0.0000e+00, 1.8961e-34],
        [0.0000e+00, 1.8961e-34, 0.0000e+00],
        [1.8961e-34, 0.0000e+00, 1.8961e-34]])


##### 创建随机的一个随机数矩阵

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.0015, 0.5940, 0.5286],
        [0.8055, 0.2488, 0.1868],
        [0.4127, 0.1654, 0.7820],
        [0.4050, 0.5514, 0.6931],
        [0.5736, 0.4044, 0.9075]])


##### 创建0元素的矩阵

In [4]:
x = torch.zeros(5,3)

In [5]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


##### 直接从已经数据创建tensor

In [6]:
x= torch.tensor([5,5,3])
print(x)

tensor([5, 5, 3])


##### 创建新的矩阵

In [7]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
# 根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x,dtype=torch.float)
print(x)
# 更新了x的dtype,保留了原始的x的size

tensor([[ 0.8425, -0.4388, -0.4415],
        [-0.8796, -0.1941,  1.6209],
        [-1.1075,  0.0803, -2.1088],
        [ 0.3202, -0.7222, -0.3312],
        [ 1.4174, -0.4448, -0.9877]])


In [9]:
print(x.size())

torch.Size([5, 3])


#### 计算操作

##### 加法操作

In [10]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.1707, -0.2280, -0.2457],
        [-0.2291,  0.6358,  1.8969],
        [-0.9142,  0.5477, -1.3587],
        [ 0.7549, -0.1467,  0.4180],
        [ 2.2174,  0.4118, -0.4257]])


In [11]:
print(torch.add(x,y))

tensor([[ 1.1707, -0.2280, -0.2457],
        [-0.2291,  0.6358,  1.8969],
        [-0.9142,  0.5477, -1.3587],
        [ 0.7549, -0.1467,  0.4180],
        [ 2.2174,  0.4118, -0.4257]])


In [12]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.1707, -0.2280, -0.2457],
        [-0.2291,  0.6358,  1.8969],
        [-0.9142,  0.5477, -1.3587],
        [ 0.7549, -0.1467,  0.4180],
        [ 2.2174,  0.4118, -0.4257]])


In [13]:
# 加法操作，inplace 操作,替换y值，类似于y+=x
y.add_(x)
print(y)

tensor([[ 1.1707, -0.2280, -0.2457],
        [-0.2291,  0.6358,  1.8969],
        [-0.9142,  0.5477, -1.3587],
        [ 0.7549, -0.1467,  0.4180],
        [ 2.2174,  0.4118, -0.4257]])


##### 转化形状

In [14]:
x = torch.randn(4,4)
y= x.view(16)
z=x.view(-1,8)  # the size -1 是根据其他维度进行计算出来的
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
torch.numel(x)  # return the number of the input tensor

16

##### tensor 与numpy 的转化

In [17]:
import numpy as np
a = np.array([1,2,3])
t = torch.as_tensor(a)
print(t)

tensor([1, 2, 3], dtype=torch.int32)


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()  # 类似于a和b，a 变了，b也跟着变，类似于numpy 中的view的操作
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
id(a),id(b)

89649368